# Generated by Django 5.0.7 on 2024-08-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_alter_task_task_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='C_task',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
