# Generated by Django 5.0.7 on 2024-08-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0004_users_t_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='C_or_Not',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
