# Generated by Django 5.0.7 on 2024-08-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0005_users_c_or_not'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='C_or_Not',
        ),
        migrations.AddField(
            model_name='task',
            name='C_or_Not',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
