# Generated by Django 5.0.7 on 2024-09-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0006_remove_users_c_or_not_task_c_or_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='EndDate',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_task',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
