# Generated by Django 5.0.7 on 2024-09-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0008_task_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
