# Generated by Django 4.2.16 on 2024-09-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0009_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='cronProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendom_num', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
