# Generated by Django 4.2.16 on 2024-09-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0010_cronproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cronProxy',
        ),
    ]
